version: "3.9"
services:
  multi-modal-env:
    image: multi-modal-env:latest
    build: .
    volumes:
      - '${PWD}/test-code:/app'                # Attach our Code folder
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 8989:8888   # Our jupyter-lab/notebook will be accessible on port 8989
    tty: true
    stdin_open: true
